<?php

namespace RestCord\Enums;

enum MessageType: int
{
    case DEFAULT = 0;
    case RECIPIENT_ADD = 1;
    case RECIPIENT_REMOVE = 2;
    case CALL = 3;
    case CHANNEL_NAME_CHANGE = 4;
    case CHANNEL_ICON_CHANGE = 5;
    case CHANNEL_PINNED_MESSAGE = 6;
    case GUILD_MEMBER_JOIN = 7;
    case USER_PREMIUM_GUILD_SUBSCRIPTION = 8;
    case USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1 = 9;
    case USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2 = 10;
    case USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3 = 11;
    case CHANNEL_FOLLOW_ADD = 12;
    case GUILD_DISCOVERY_DISQUALIFIED = 14;
    case GUILD_DISCOVERY_REQUALIFIED = 15;
    case GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING = 16;
    case GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING = 17;
    case THREAD_CREATED = 18;
    case REPLY = 19;
    case CHAT_INPUT_COMMAND = 20;
    case THREAD_STARTER_MESSAGE = 21;
    case GUILD_INVITE_REMINDER = 22;
    case CONTEXT_MENU_COMMAND = 23;
}